### ISSUE TITLE
error in production build

### ISSUE THREAD

**Issue by AnandanRajkumar** [nodebeats/nodebeats#15]
i followed the below steps for production build

npm run build:all

npm run serve

then i browse the below url

http://localhost:3005 -loads landing page;

http://localhost:3005/admin - white page loaded

if i inspect  this page throw error "/admin" route not found please help me solve this

thanks

**Comment by avsek477** [comment]
Make sure you don't use any DOM elements such as window or document. Or any npm packages that uses window or document.

**Comment by gowtham-s** [comment]
same here!

**Comment by avsek477** [comment]
@AnandanRajkumar 
To summarize running the application in production, here is an overview. When you run "npm run build:all", it is going to build both client and admin dist file, the client with SSR files are located in dist folder while the admin files are located in dist-admin folder. [NOTE: Make sure you change the parameters for production inside "/admin/src/admin-app/shared/configs/env.config.ts" file]. So in order to run these pre built aot angular files, we create two servers: one is the angular server which we can run by navigating to the admin folder and running the "npm run serve" command. What this does is it creates an angular server that runs our dist folder and we can navigate on to "localhost:4005" in our browser and see the server side rendered version of our landing page.

Now, we create a second server using node.js where we serve our dist-admin folder. In order to do this, open a new terminal and navigate to the root directory and run command "NODE_ENV=production npm start". What this does is it creates a node server and serves our dist-admin folder and we can see the result by navigating on to "localhost:3005/admin" in our browser and see the login page. [NOTE: This takes a bit more time to load for the first time(may be 1 or 2 minutes or more because admin side is too bulky and the browser has to download all the files and parse it) but should run fine when you serve this through nginx on the cloud server]. Hope this helps!!!
