### ISSUE TITLE
not working in production as documented

### ISSUE THREAD

**Issue by gowtham-s** [nodebeats/nodebeats#16]
In production mode, I'm able to access the landing page through http://localhost:4005 but when I try http://localhost:3005 or http://localhost:3005/admin as documented, it is not working!

**Comment by avsek477** [comment]
Can you post the link where it is written so ? We might have missed somewhere to update the documentation.

**Comment by avsek477** [comment]
You can also refer here: https://www.nodebeats.com/documentation/getting-started/1/set-up-development-environment

**Comment by avsek477** [comment]
http://localhost:3005/admin should work.. may be it is taking too long to load. The admin package is a bit too bulky so it takes time to load login page for the first time. This should work fine once you upload the code in the server.

**Comment by gowtham-s** [comment]
It says localhost:3500/admin - This site can’t be reached when localhost:4005 shows the client(landing page). I'm not receiving any errors either.

**Comment by avsek477** [comment]
@gowtham-s  i did not understand the problem.. could you please elaborate? P.S. There is no 3500 port mentioned in nodebeats.

To summarize running the application in production, here is an overview. When you run "npm run build:all", it is going to build both client and admin dist file, the client with SSR files are located in dist folder while the admin files are located in dist-admin folder. [NOTE: Make sure you change the parameters for production inside "/admin/src/admin-app/shared/configs/env.config.ts" file]. So in order to run these pre built aot angular files, we create two servers: one is the angular server which we can run by navigating to the admin folder and running the "npm run serve" command. What this does is it creates an angular server that runs our dist folder and we can navigate on to "localhost:4005" in our browser and see the server side rendered version of our landing page. 

Now, we create a second server using node.js where we serve our dist-admin folder. In order to do this, open a new terminal and navigate to the root directory and run command "NODE_ENV=production npm start". What this does is it creates a node server and serves our dist-admin folder and we can see the result by navigating on to "localhost:3005/admin" in our browser and see the login page. [NOTE: This takes a bit more time to load for the first time(may be 1 or 2 minutes or more because admin side is too bulky and the browser has to download all the files and parse it) but should run fine when you serve this through nginx on the cloud server]. Hope this helps!!!

**Comment by avsek477** [comment]
Also, try loading in incognito or firefox as well. Chrome does throw that error sometimes when it loads from cache.

**Comment by gowtham-s** [comment]
@avsek477 thanks for the clear explanation and sorry that the mentioned 3500 was a typo. I was trying to say 'localhost:3005/admin'. 
Now let me clearly say what is happening from my side. I tried building both the client and admin with the command 'npm run build:all' as documented and succeeded(I now see two folders dist and dist-admin). When I come to the root folder again and run 'npm start' or nodemon and check localhost:3005/admin, it says '{ "message" : 'Internal server error' }. I'm running the application from a windows machine and setting node environment to production with this command - 'SET NODE_ENV=production'
When I check ErrorLog collection from mongodb, I see a logged error message something like "Not Found eroro hahah e" in index.js from route folder(H:\\nodebeats\\lib\\routes\\index.js:139:23\n). And this is what I see in the root folder terminal log "GET /admin 500 29.753 ms - 35". I think admin route for serving static files is missing in the index.js folder. Please correct me if I'm wrong

Thanks,
Gowtham

**Comment by avsek477** [comment]
I don't know how you got that haha error, I clearly commented out that line as you can see in the lib/routes/index.js file. You might have uncommented out the lines. But the error here is clearly suggesting that server did not find the /admin route and this is only possible if you run server in the development environment. (My say here is that your node environment isn't set to production). You can try and directly set the NODE_ENV temporarily by typing the command as I mentioned earlier using "NODE_ENV=production npm start". However, you can try one more approach. Check line numbers 144 and 156 of app.js file. The routes for serving the static files are written there. You can copy the admin.use() code of production and paste in the development as well. It should run. 

I checked in my end. The code working fine if I set my node environment to production. And thank you for using Nodebeats. Means a lot.

**Comment by gowtham-s** [comment]
Thanks, the code is working fine if I set my node env to production. However, the document is all about Linux for production. Had I known NODE_ENV=production will only work on Linux but not on windows, things would have been easier. Anyways, Nodebeats works great and I love using it. 

Have a nice weekend!

**Comment by avsek477** [comment]
Sorry, I haven't used windows in years. But you can email me the
inconveniences you are facing and we will change it accordingly in the
documentation. Thank you !!!
